#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

PROJECT="${PROJECT:-bffs-assignments}"
echo "  Target project: $PROJECT   (override with PROJECT=<id> if wrong)"
SHELL_DEFAULT="1SqMdIVBKMYRfOaGw4TucVVPpjqm4kvXqEZJo6W1HWms"
BASE="https://console.cloud.google.com/auth"

banner "Google OAuth for the SOO sheets push"

# ── Stage 1: Google Cloud project ─────────────────────────────────────────
stage "Google Cloud — project"
say "You already created the project (bffs-assignments) — this stage confirms it."
open_url "https://console.cloud.google.com/projectcreate"
step "If the project picker (top-left) isn't on 'bffs-assignments', pick it."
step "Only create a new project if you want a different one."
pause "Confirm the console says bffs-assignments."

# ── Stage 2: Enable the Google Sheets API ─────────────────────────────────
stage "Google Sheets API — enable"
say "The OAuth client can only call APIs that are enabled on the project."
open_url "https://console.cloud.google.com/apis/library/sheets.googleapis.com?project=${PROJECT}"
step "Confirm the project picker shows ${PROJECT}."
step "Click ENABLE on the Google Sheets API page."
pause "Confirm you saw the 'API enabled' confirmation."

# ── Stage 3: Consent (Google Auth platform → Audience + Data access) ──────
stage "Consent screen — Audience + Data access"
say "The new Google Auth platform keeps the consent screen in three tabs:"
note "  Branding · Audience · Data access   (left sidebar under 'Google Auth platform')"
open_url "${BASE}/audience?project=${PROJECT}"
step "Says 'not configured yet'? Click Get Started, then:"
step "  1) Branding → App name 'BFFS Assignment Push' + User support email → Next"
step "  2) Audience → user type EXTERNAL → Next"
step "  3) Contact info → your email → Next; agree to User Data Policy → Create"
step "Already configured? In Audience, click TEST USERS → Add users → add your own"
step "Google email (required in Testing mode) → Save."
open_url "${BASE}/data-access?project=${PROJECT}"
step "Under Data access → ADD OR REMOVE SCOPES → search 'Google Sheets API' → tick"
step "the spreadsheet scope (…/auth/spreadsheets) → SAVE. Keep any default scopes too."
pause "Confirm: a test user (your email) is set, and the spreadsheets scope is saved."

# ── Stage 4: OAuth client (Desktop) from the Clients page ─────────────────
stage "OAuth client — Desktop (Clients page)"
say "Clients are created under 'Clients' in the new platform — not the old"
say "'Create credentials → OAuth client ID' menu."
open_url "${BASE}/clients?project=${PROJECT}"
step "Click CREATE CLIENT (button above the clients list)."
step "Application type: DESKTOP APP  ← what makes the local redirect work."
step "Name: 'assignments-push'. → CREATE."
step "The created-client dialog shows the CLIENT ID and CLIENT SECRET — copy both."
ask GOOGLE_CLIENT_ID "Paste the Client ID:"
step "Secret is in the same dialog (or ⋯ → Download JSON → client_secret)."
ask_secret GOOGLE_CLIENT_SECRET "Paste the Client Secret:"
write_env GOOGLE_CLIENT_ID     "$GOOGLE_CLIENT_ID"
write_env GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"

# ── Stage 5: authorize + refresh token ────────────────────────────────────
stage "Authorize — capture the refresh token"
say "One-time browser consent. A tiny local server captures the code Google sends"
say "back and exchanges it for a refresh token (persisted to .env)."
step "Make sure you're signed into your Google account in the browser first."
ask GOOGLE_SHEET_ID "Google Sheet ID to authorize against:"
[[ -z "$GOOGLE_SHEET_ID" ]] && GOOGLE_SHEET_ID="$SHELL_DEFAULT" && note "(using the test raid sheet id)"
write_env GOOGLE_SHEET_ID "$GOOGLE_SHEET_ID"
note "If you see redirect_uri_mismatch: open the client in Clients → edit → add"
note "'http://127.0.0.1:8787' as an authorized redirect URI (Desktop type usually"
note "covers the loopback already) → save → re-run the wizard / stage."
cat > .cache/oauth-helper.mjs <<'HELPEREOF'
import http from 'node:http';
import fs from 'node:fs';
import crypto from 'node:crypto';
const [clientId, clientSecret, sheetId] = process.argv.slice(2);
const port = 8787;
const redirectURI = `http://127.0.0.1:${port}/`;
const state = Math.random().toString(36).slice(2);
const verifier = crypto.randomBytes(48).toString('base64url');
const challenge = crypto.createHash('sha256').update(verifier).digest('base64url');
const authUrl = 'https://accounts.google.com/o/oauth2/v2/auth'
  + `?client_id=${encodeURIComponent(clientId)}`
  + `&redirect_uri=${encodeURIComponent(redirectURI)}`
  + `&response_type=code&scope=${encodeURIComponent('https://www.googleapis.com/auth/spreadsheets')}`
  + '&access_type=offline&prompt=consent'
  + '&code_challenge=' + challenge + '&code_challenge_method=S256'
  + `&state=${state}`;
fs.writeFileSync('.cache/oauth-url.txt', authUrl);
const server = http.createServer(async (req, res) => {
  const u = new URL(req.url, `http://127.0.0.1:${port}`);
  if (u.pathname !== '/' || u.searchParams.get('state') !== state) { res.writeHead(400); res.end('bad request'); return; }
  const code = u.searchParams.get('code');
  if (!code) { res.writeHead(400); res.end('no code'); return; }
  res.writeHead(200, { 'Content-Type': 'text/html' });
  res.end('<h3>Authorized — you can close this tab.</h3>');
  server.close();
  try {
    const tok = await fetch('https://oauth2.googleapis.com/token', {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({ code, client_id: clientId, client_secret: clientSecret, redirect_uri: redirectURI, grant_type: 'authorization_code', code_verifier: verifier }),
    });
    const tj = await tok.json();
    if (!tj.refresh_token) throw new Error('no refresh_token: ' + JSON.stringify(tj).slice(0, 200));
    fs.writeFileSync('.cache/oauth-refresh.txt', tj.refresh_token);
    const sheet = await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(sheetId)}?fields=properties(title)`, { headers: { Authorization: `Bearer ${tj.access_token}` } });
    const sj = await sheet.json();
    fs.writeFileSync('.cache/oauth-result.txt', `token ok (expires in ${tj.expires_in}s) · sheet: ${sj.properties?.title ?? JSON.stringify(sj).slice(0, 160)}`);
    process.exit(0);
  } catch (e) {
    fs.writeFileSync('.cache/oauth-result.txt', 'FAILED: ' + e.message);
    process.exit(1);
  }
});
server.listen(port, '127.0.0.1', () => { console.log('listening for the Google redirect on http://127.0.0.1:' + port + '/ ...'); });
HELPEREOF
node .cache/oauth-helper.mjs "$GOOGLE_CLIENT_ID" "$GOOGLE_CLIENT_SECRET" "$GOOGLE_SHEET_ID" &
HELPER_PID=$!
sleep 2
if [[ -f .cache/oauth-url.txt ]]; then open_url "$(cat .cache/oauth-url.txt)"; fi
wait "$HELPER_PID" || { warn "authorization did not complete — check .cache/oauth-result.txt"; pause "Press Enter to finish"; exit 1; }
GOOGLE_REFRESH_TOKEN=$(cat .cache/oauth-refresh.txt)
write_env GOOGLE_REFRESH_TOKEN "$GOOGLE_REFRESH_TOKEN"
note "Verification: $(cat .cache/oauth-result.txt 2>/dev/null || echo 'none')"

finish
